# Generated by Django 4.1.2 on 2022-10-16 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pack',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('29ac1f38-4da0-11ed-b0fd-c5c6ef34ccc9'), editable=False, primary_key=True, serialize=False)),
                ('piles', models.IntegerField()),
                ('startDate', models.DateField(auto_now=True)),
                ('retiret', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cells.series')),
            ],
        ),
    ]
