# Generated by Django 4.1.2 on 2022-10-16 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b195aec2-4da6-11ed-b0fd-c5c6ef34ccc9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
